#!/bin/bash
curl https://raw.githubusercontent.com/dordio/dotfiles/master/bashrc >> .bashrc
curl https://raw.githubusercontent.com/dordio/dotfiles/master/vimrc >> .vimrc
touch .tmux.conf
curl https://raw.githubusercontent.com/dordio/dotfiles/master/tmux.conf >> .tmux.conf
